batch_size: 32
save_path: /tmp/results/results_gaussians_three_flows/

methods:

  "Adaptive i-SIR":
    name: adaptive_isir
    save_name: adaptive_isir
    neutralize: false
    warmup_steps: 0
    params:
      N: 40

  "Adaptive IMH":
    name: adaptive_imh
    save_name: adaptive_imh
    neutralize: false
    warmup_steps: 0
    params:
      dummy: 0

  "Adaptive IS":
    name: adaptive_is
    save_name: adaptive_is
    neutralize: false
    warmup_steps: 0
    scheduler:
      params:
        N:
          16: 11000
          32: 12000
          64: 13000
          128: 14000
          256: 15000

  MALA:
    name: mala
    save_name: mala
    neutralize: false
    warmup_steps: 0
    params:
      step_size: 0.01
      target_acceptance: 0.75

  "NeuTra with MALA":
    name: mala
    save_name: neutra_mala
    neutralize: true
    warmup_steps: 0
    params:
      step_size: 0.01
      target_acceptance: 0.75

  "Transport ESS":
    name: ess
    save_name: tess
    neutralize: true
    warmup_steps: 0
    params:
      dummy: 0

  "NeuTra Ex²MCMC with MALA":
    name: ex2mcmc
    save_name: neutra_ex2mcmc_mala
    neutralize: true
    warmup_steps: 0
    params:
      N: 50
      local_sampler: 'mala'
      n_local_mcmc: 20
    local_sampler_params:
      step_size: 0.01
      target_acceptance: 0.75

  "FlEx²MCMC with MALA":
    name: flex2mcmc
    save_name: flex2mcmc_mala
    neutralize: false
    warmup_steps: 0
    params:
      N: 40
      local_sampler: 'mala'
      n_local_mcmc: 50
    local_sampler_params:
      step_size: 0.01
      target_acceptance: 0.75

  "AdaptiveMCMC with MALA":
    name: adaptive_mcmc
    save_name: adaptive_mcmc_mala
    neutralize: false
    warmup_steps: 0
    params:
      local_sampler: 'mala'
      n_local_mcmc: 50
    local_sampler_params:
      step_size: 0.01
      target_acceptance: 0.75
