save_name: flex2mcmc

methods:


  "FlEx²MCMC with MALA (N = 40 | n_local_mcmc = 5 | loss_type = forward_kl)":
    name: flex2mcmc
    save_name: flex2mcmc_mala
    neutralize: false
    warmup_steps: 0
    n_steps: 512
    loss_type: forward_kl
    params:
      local_sampler: 'mala'
      n_local_mcmc: 5
      N: 40
    local_sampler_params:
      step_size: 0.001
      target_acceptance: 0.75


  "FlEx²MCMC with MALA (N = 40 | n_local_mcmc = 10 | loss_type = forward_kl)":
    name: flex2mcmc
    save_name: flex2mcmc_mala
    neutralize: false
    warmup_steps: 0
    n_steps: 512
    loss_type: forward_kl
    params:
      local_sampler: 'mala'
      n_local_mcmc: 10
      N: 40
    local_sampler_params:
      step_size: 0.001
      target_acceptance: 0.75


  "FlEx²MCMC with MALA (N = 40 | n_local_mcmc = 15 | loss_type = forward_kl)":
    name: flex2mcmc
    save_name: flex2mcmc_mala
    neutralize: false
    warmup_steps: 0
    n_steps: 512
    loss_type: forward_kl
    params:
      local_sampler: 'mala'
      n_local_mcmc: 15
      N: 40
    local_sampler_params:
      step_size: 0.001
      target_acceptance: 0.75


  "FlEx²MCMC with MALA (N = 40 | n_local_mcmc = 20 | loss_type = forward_kl)":
    name: flex2mcmc
    save_name: flex2mcmc_mala
    neutralize: false
    warmup_steps: 0
    n_steps: 512
    loss_type: forward_kl
    params:
      local_sampler: 'mala'
      n_local_mcmc: 20
      N: 40
    local_sampler_params:
      step_size: 0.001
      target_acceptance: 0.75


  "FlEx²MCMC with MALA (N = 70 | n_local_mcmc = 5 | loss_type = forward_kl)":
    name: flex2mcmc
    save_name: flex2mcmc_mala
    neutralize: false
    warmup_steps: 0
    n_steps: 512
    loss_type: forward_kl
    params:
      local_sampler: 'mala'
      n_local_mcmc: 5
      N: 70
    local_sampler_params:
      step_size: 0.001
      target_acceptance: 0.75


  "FlEx²MCMC with MALA (N = 70 | n_local_mcmc = 10 | loss_type = forward_kl)":
    name: flex2mcmc
    save_name: flex2mcmc_mala
    neutralize: false
    warmup_steps: 0
    n_steps: 512
    loss_type: forward_kl
    params:
      local_sampler: 'mala'
      n_local_mcmc: 10
      N: 70
    local_sampler_params:
      step_size: 0.001
      target_acceptance: 0.75


  "FlEx²MCMC with MALA (N = 70 | n_local_mcmc = 15 | loss_type = forward_kl)":
    name: flex2mcmc
    save_name: flex2mcmc_mala
    neutralize: false
    warmup_steps: 0
    n_steps: 512
    loss_type: forward_kl
    params:
      local_sampler: 'mala'
      n_local_mcmc: 15
      N: 70
    local_sampler_params:
      step_size: 0.001
      target_acceptance: 0.75


  "FlEx²MCMC with MALA (N = 70 | n_local_mcmc = 20 | loss_type = forward_kl)":
    name: flex2mcmc
    save_name: flex2mcmc_mala
    neutralize: false
    warmup_steps: 0
    n_steps: 512
    loss_type: forward_kl
    params:
      local_sampler: 'mala'
      n_local_mcmc: 20
      N: 70
    local_sampler_params:
      step_size: 0.001
      target_acceptance: 0.75


  "FlEx²MCMC with MALA (N = 90 | n_local_mcmc = 5 | loss_type = forward_kl)":
    name: flex2mcmc
    save_name: flex2mcmc_mala
    neutralize: false
    warmup_steps: 0
    n_steps: 512
    loss_type: forward_kl
    params:
      local_sampler: 'mala'
      n_local_mcmc: 5
      N: 90
    local_sampler_params:
      step_size: 0.001
      target_acceptance: 0.75


  "FlEx²MCMC with MALA (N = 90 | n_local_mcmc = 10 | loss_type = forward_kl)":
    name: flex2mcmc
    save_name: flex2mcmc_mala
    neutralize: false
    warmup_steps: 0
    n_steps: 512
    loss_type: forward_kl
    params:
      local_sampler: 'mala'
      n_local_mcmc: 10
      N: 90
    local_sampler_params:
      step_size: 0.001
      target_acceptance: 0.75


  "FlEx²MCMC with MALA (N = 90 | n_local_mcmc = 15 | loss_type = forward_kl)":
    name: flex2mcmc
    save_name: flex2mcmc_mala
    neutralize: false
    warmup_steps: 0
    n_steps: 512
    loss_type: forward_kl
    params:
      local_sampler: 'mala'
      n_local_mcmc: 15
      N: 90
    local_sampler_params:
      step_size: 0.001
      target_acceptance: 0.75


  "FlEx²MCMC with MALA (N = 90 | n_local_mcmc = 20 | loss_type = forward_kl)":
    name: flex2mcmc
    save_name: flex2mcmc_mala
    neutralize: false
    warmup_steps: 0
    n_steps: 512
    loss_type: forward_kl
    params:
      local_sampler: 'mala'
      n_local_mcmc: 20
      N: 90
    local_sampler_params:
      step_size: 0.001
      target_acceptance: 0.75
